# Generated by Django 5.0.6 on 2024-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_room_stations"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_station",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="lang",
            field=models.CharField(default="english", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="tag",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
