# Generated by Django 5.0.6 on 2024-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_room_votes_to_skip"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_station_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="current_station",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
