# Generated by Django 5.0.6 on 2024-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_room_current_station_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="isPlaying",
            field=models.BooleanField(default=True),
        ),
    ]
